Jj = int(input())
Tb = int(input())
phi = 22/7
V = phi*Jj*Jj*Tb
L = 2*phi*Jj*(Jj+Tb)
K = 2*phi*Jj
print("Volume = ",round(V,2))
print("Luas = ",round(L,2))
print("Keliling = ",round(K,2))

JJ,TB = input(). split()
JJ = int(JJ)
TB = int(TB)
phi = 22/7
v = phi*JJ*JJ*TB
l= 2*phi*JJ*(JJ+TB)
k = 2*phi*JJ
print("Volume = ",round(v,2))
print("Luas = ",round(l,2))
print("Keliling = ",round(k,2))