print("##############################")
print("#                            #")
print("#     Riyo Aurora Guison     #")
print("#       2210817310016        #")
print("#                            #")
print("##############################")