Nama =input("Nama :")
NIM =input("NIM :")
Kelas_Paralel =input("Kelas Paralel :")
TTL =input("Tempat/Tanggal Lahir :")
Alamat =input("Alamat :")
Hobby =input("Hobby :")
NO_HP =input("No.HP :\n")
print("Nama                         :",Nama)
print("NIM                          :",NIM)
print("Kelas Paralel                :",Kelas_Paralel)
print("Tempat/Tanggal Lahir         :",TTL)
print("Alamat                       :",Alamat)
print("Hobby                        :",Hobby)
print("No.HP                        :",NO_HP)
